### ISSUE TITLE
buildSVFModule performance issue on version > 2.4

### ISSUE THREAD

**Issue by zu1k** [SVF-tools/SVF#1144]
I encountered serious performance issue when calling `buildSVFModule` on a 7MB bc file using SVF version `2.6`, which caused the function to take over 20 minutes to execute without returning.

When I was using SVF `2.4`, this took only a few seconds. And it looks like SVF `2.5` and SVF `master` also have this problem. 

~~I didn't read the changes to the SVF code in depth, but I found through the release log that in both the `2.5` and `2.6` releases, you tried to remove the LLVM dependence and added the CFL implementation, I don't know if this is the cause of the performance issues, especially with the CFl implementation.~~

I attach here the bc files for SVF `master`, `2.4` and `2.5`, all LLVM versions match the version specified in the SVF releases.

Performance issues can be found when using `wpa` for analysis, such as exporting call graph or control flow graph, where version `2.4` has a significantly shorter analysis process before exporting than the newer versions, while the master version is slow to enter the graph export process.

[bc.tar.gz](https://github.com/SVF-tools/SVF/files/11983853/bc.tar.gz)

**Comment by yuleisui** [comment]
Have you tried to use the current upstream SVF. We have fixed that issue in SVF-2.6. Please have a try and let me know.

**Comment by zu1k** [comment]
I tried SVF-2.6 and the latest master branch, the problem still exists.

**Comment by yuleisui** [comment]
Are you saying ‘ buildSVFModule’ took long time and can’t terminate? Could you dig a bit more to see which method in the current upstream takes more time or can’t terminate? Please put some stats if you have

**Comment by zu1k** [comment]
Yes, buildSVFModule unable to return within expected time. I'll try to find out what's getting in the way later.

**Comment by yuleisui** [comment]
Let me know which methods inside buildSVFModule took long time to execute

**Comment by zu1k** [comment]
If you have time, try the bc file I provided, I'm sure you know more about SVF than I do and therefore have a better chance of finding the cause.

**Comment by yuleisui** [comment]
Let me have a try, btw, you could also help pin where is the performance bottleneck inside `buildSVFModule `

**Comment by yuleisui** [comment]
Just localized the problem because of string handling when copying all LLVM values' strings https://github.com/SVF-tools/SVF/blob/04c226d2e3524beef9de1106ce2b54125b816d4a/svf-llvm/lib/LLVMModule.cpp#L313-L318, https://github.com/SVF-tools/SVF/blob/04c226d2e3524beef9de1106ce2b54125b816d4a/svf-llvm/lib/LLVMModule.cpp#L1015-L1031 and https://github.com/SVF-tools/SVF/blob/04c226d2e3524beef9de1106ce2b54125b816d4a/svf-llvm/lib/LLVMModule.cpp#L1056-L1059. We will look into it.

**Comment by zu1k** [comment]
I made a simple perf, hope this will help you.

![Screenshot from 2023-07-08 10-26-11](https://github.com/SVF-tools/SVF/assets/42370281/092b5656-3580-4245-af45-df30aca2b166)

**Comment by zu1k** [comment]
I made a simple perf, hope this will help you.

![Screenshot from 2023-07-08 11-02-05](https://github.com/SVF-tools/SVF/assets/42370281/970ac52c-ad28-4342-9d4c-65bee6fc9841)

![Screenshot from 2023-07-08 11-01-42](https://github.com/SVF-tools/SVF/assets/42370281/dd0ad888-ca18-4f8c-9992-c021adeaab02)

**Comment by zu1k** [comment]
> because of string handling when copying all LLVM values' strings

Is this necessary? Or can we lazy load this while using.

**Comment by yuleisui** [comment]
> > because of string handling when copying all LLVM values' strings
> 
> Is this necessary? Or can we lazy load this while using.

Yes, that could save time and was what we did in the previous versions before we have SVFIR. We will see how to reduce this overhead.

**Comment by zu1k** [comment]
> was what we did in the previous versions before we have SVFIR.

A non-topic related question, for the following code, if I use SVF-2.4, does this make some difference? Such as performance difference and analysis accuracy difference, compared to using the latest 2.6 version.

For me, I only need ICFG and SVFG, not the other analysis tools in the SVF project, e.g. SABER etc. are not my concern.

```
LLVMModuleSet::getLLVMModuleSet()->preProcessBCs( moduleNameVec );

std::cout << "1. build SVFModule" << std::endl;
SVFModule* svfModule = LLVMModuleSet::getLLVMModuleSet()->buildSVFModule( moduleNameVec );

/// Build Program Assignment Graph (SVFIR)
std::cout << "2. build SVFIR / PAG" << std::endl;
SVFIRBuilder builder( svfModule );
SVFIR* pag = builder.build();

/// Create Andersen's pointer analysis
std::cout << "3. do Andersen's pointer analysis" << std::endl;
Andersen* ander = AndersenWaveDiff::createAndersenWaveDiff( pag );

/// ICFG
std::cout << "4. get ICFG" << std::endl;
ICFG* icfg = pag->getICFG();

/// Sparse value-flow graph (SVFG)
std::cout << "5. build Full SVFG" << std::endl;
SVFGBuilder svfBuilder;
SVFG* svfg = svfBuilder.buildFullSVFG( ander );

// do some travel through ICFG and SVFG on my own
```

**Comment by yuleisui** [comment]
The performance will be the same as 2.4 if you remove the three pieces of code for string handling I posted.

**Comment by zu1k** [comment]
> The performance will be the same as 2.4 if you remove the three pieces of code for string handling I posted.

I did a rest, execute the same command `time wpa -ander -svfg  ./xmllint.bc`.

SVF-2.4, LLVM 13.0.0

```
real	3m16.103s
user	2m58.197s
sys	0m9.935s
```

SVF-2.6, LLVM 14.0.0

```
real    5m27.038s
user    5m24.552s
sys     0m1.852s
```

I would like to know the difference in accuracy between SVF-2.6 and SVF-2.4 in terms of pointer analysis and SVFG construction.

**Comment by yuleisui** [comment]
This is hard and you need to collect SVF's outputs and compare them. 2.4 is no longer maintained.

**Comment by yuleisui** [comment]
@xudon9 will make a patch to fix the string copy performance issue soon.

**Comment by yuleisui** [comment]
> > The performance will be the same as 2.4 if you remove the three pieces of code for string handling I posted.
> 
> I did a test, execute the same command `time wpa -ander -svfg ./xmllint.bc`.
> 
> SVF-2.4, LLVM 13.0.0
> 
> ```
> real	3m16.103s
> user	2m58.197s
> sys	0m9.935s
> ```
> 
> SVF-2.6, LLVM 14.0.0
> 
> ```
> real    5m27.038s
> user    5m24.552s
> sys     0m1.852s
> ```
> 
> I would like to know the difference in accuracy between SVF-2.6 and SVF-2.4 in terms of pointer analysis and SVFG construction.

How did you get the results, you mentioned there is an assertion error due to unique definition

**Comment by zu1k** [comment]
> How did you get the results, you mentioned there is an assertion error due to unique definition

Since I counted the number of times the assert was triggered and it only appeared once in my target bc file, I guessed that the error might not be harmful to my subsequent processes, so I temporarily removed the assert.

Perhaps another assert will be triggered when `getDef` is used elsewhere, but currently in my target bc file, it happens not to be triggered, which allows me to continue the process.

**Comment by yuleisui** [comment]
Once Xudong pushes the patch to fix the string issue, can you report again the llvm values that trigger the assertion in that issue.

**Comment by zu1k** [comment]
> Once Xudong pushes the patch to fix the string issue, can you report again the llvm values that trigger the assertion in that issue.

Sure

**Comment by zu1k** [comment]
Testing of the latest master branch, performance issues have been fixed.

SVF-master, LLVM 14.0.0

```
# time wpa -ander -svfg ./xmllint.bc
......

real	4m14.442s
user	4m12.688s
sys	0m1.619s
```

Thank you for your prompt response and contribution!
